version: '3.4'

services:
  app:
    image: threax/files
    build:
      context: .
      dockerfile: Files/Dockerfile
    networks:
      - appnet
    volumes:
      - type: bind
        source: ../TrustedRoots
        target: /usr/local/share/ca-certificates
      - type: bind
        source: ../DevData/Files
        target: /appdata
    labels:
      - "threax.nginx.host=files.dev.threax.com"

networks:
  appnet:
    external: true